# -*- coding: utf-8 -*-
"""DSI_Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vKbMlf7acjW5wERpJ4GOYqwGSwwk-OX_
"""

from shapely.geometry import Point, LineString, Polygon

Hexagon = Polygon([(50,-100), (-50,-100), (-100,0), (-50,100), (50,100), (100,0)])

Hexagon

P = Point(24, 60)

P.within(Hexagon)

T = Polygon([P, (-50,100), (50,100)])
T

print(T.centroid)

P=(T.centroid)

print(P)

T = Polygon([P, (-50,100), (-100,0)])
T

print(T.centroid)

P=(T.centroid)
print(P)

from math import sqrt
from random import randrange, random
from matplotlib import pyplot

vectors = [(-1.,0),(.5,sqrt(3.)/2.),(.5,-sqrt(3.)/2.)]

def randinunithex():
    x = randrange(3);
    (v1,v2) = (vectors[x], vectors[(x+1)%3])
    (x,y) = (random(),random())
    return (x*v1[0]+y*v2[0],x*v1[1]+y*v2[1])

for n in range(10000):
    v = randinunithex()
    pyplot.plot([v[0]],[v[1]],'ro')

pyplot.show()

